Konsumere nye apier fra veilarbarena uten fnr
navikt/veilarboppfolging pull request #579
Opened 2023-10-25 08:51 UTC by klaramargrethehelgemo

2023-10-25 11:36 UTC, slovrid commented on src/main/java/no/nav/veilarboppfolging/client/veilarbarena/PersonRequest.java
> +}
Bytt gjerne til Java Record, da dette har samme semantikk som `lombok.Data` og vi da slipper å dra inn denne avhengigheten her.

```suggestion
public record PersonRequest(
  Fnr fnr;
) {}
```

2023-10-25 11:36 UTC, slovrid commented on src/main/java/no/nav/veilarboppfolging/client/veilarbarena/VeilarbarenaClientImpl.java
> +                .url(joinPaths(veilarbarenaUrl, "/api/v2/oppfolgingsbruker/"))
Fjerne trailing-slash:
```suggestion
                .url(joinPaths(veilarbarenaUrl, "/api/v2/oppfolgingsbruker"))
```

2023-10-25 11:36 UTC, slovrid commented on src/main/java/no/nav/veilarboppfolging/client/veilarbarena/VeilarbarenaClientImpl.java
> +                .url(joinPaths(veilarbarenaUrl, "/api/v2/oppfolgingsstatus/"))
Fjerne trailing-slash:
```suggestion
                .url(joinPaths(veilarbarenaUrl, "/api/v2/oppfolgingsstatus"))
```

2023-10-25 11:37 UTC, slovrid requested changes
Se kommentarer

2023-10-25 13:31 UTC, dragutin-nav approved these changes

2023-10-31 13:51 UTC, dragutin-nav submitted a review, later dismissed

2023-11-01 18:18 UTC, slovrid commented on src/main/java/no/nav/veilarboppfolging/client/veilarbarena/VeilarbarenaClientImpl.java
> +                .url(joinPaths(veilarbarenaUrl, "/api/v2/oppfolgingsbruker/hent"))
```suggestion
                .url(joinPaths(veilarbarenaUrl, "/api/v2/hent-oppfolgingsbruker"))
```

2023-11-01 18:18 UTC, slovrid commented on src/main/java/no/nav/veilarboppfolging/client/veilarbarena/VeilarbarenaClientImpl.java
> +                .url(joinPaths(veilarbarenaUrl, "/api/v2/oppfolgingsstatus/hent"))
```suggestion
                .url(joinPaths(veilarbarenaUrl, "/api/v2/hent-oppfolgingsstatus"))
```

2023-11-01 18:19 UTC, slovrid requested changes
Endre til `hent-xxx` (se kommentarer)

2023-11-02 09:42 UTC, JulieHillRoa approved these changes

2023-11-02 09:43 UTC, slovrid approved these changes

2023-11-02 09:43 UTC, merged