sjekker om bruker har aktive tiltaksdeltakelser (komet) før avsluttin…
navikt/veilarboppfolging pull request #641
Opened 2024-06-05 07:53 UTC by tiafiring

…g av oppfølging

Vi i Komet og Hans Petter har blitt enige om at det ikke bør være mulig å avslutte oppfølging hvis bruker har aktive tiltaksdeltakelser. I første omgang sjekker vi deltakelser hos Komet, men man kan fint legge til en sjekk mot f.eks. Team Tiltak også.

2024-06-05 07:54 UTC, tiafiring commented on src/main/java/no/nav/veilarboppfolging/service/OppfolgingService.java
> +        Fnr fnr = authService.getFnrOrThrow(aktorId);
Dette her synes jeg er skikkelig kjipt å gjøre. Er det slik at fnr alltid vil ligge i cachen her slik at det ikke blir et ekstra utgående kall? Hvis ikke, er det greit om jeg heller tar inn både fnr og aktørid?

2024-06-05 10:55 UTC, holymaloney commented
Jeg brukte litt tid på denne for å sikre at dette fungerer for praktiske formål. 
For å oppsummere:
Så langt jeg kan se er det to caser der oppfølging avsluttes:
1. arena-status endret (kafkamelding fra veilarbarena som plukker opp endringer på et materialisert view i arena)
2. synkront kall (fra visittkortet)
I det første tilfellet (hvis bruker har iserv-status) avsluttes ikke oppfølging umiddelbart, men bruker legges til en utmeldingstabell. Og en batch plukker ut brukere som har hatt isers mer enn 28 dager og forsøker å avslutte oppfølging.
Jeg har sjekket at i dette tilfellet vil man forsøke å avslutte bruker på nytt dersom det ikke lykkes etter 28 dager. Dette er jo litt nyttig, slik at bruker faktisk får avsluttet oppfølging hvis tiltaket avsluttes uten at man trenger å gjøre noe mer fra veileders side. 
For det andre (synkrone) tilfellet, så vil jo oppfølging for bruker ikke blir avsluttet hvis bruker har et tiltak, men vi får ikke kommunisert med veileder hvorfor. Jeg tror vi må utvide  AvslutningStatus med et nytt felt 'aktivtTiltak' e.l. , og gjøre en liten justering i visittkortet, slik at veileder får en fornuftig feilmelding.
https://github.com/navikt/veilarboppfolging/blob/8b952825ef6156532b2e09c23ac9d4304e337de7/src/main/java/no/nav/veilarboppfolging/service/OppfolgingService.java#L420

2024-06-05 11:01 UTC, holymaloney requested changes
Ser fint ut, men har noen tilbakemeldinger som du kan ta stilling til.

2024-06-05 11:01 UTC, holymaloney commented on src/main/kotlin/no/nav/veilarboppfolging/client/amttiltak/DeltakerDto.kt
Jeg liker gjerne å unngå at andre domener lekker inn hvis vi kan unngå det, men av og til må man være litt pragmatisk. I dette tilfellet kunne dere vurdert å eksponere et mer spesialisert endepunkt for dette formålet?

2024-06-05 11:32 UTC, tiafiring commented on src/main/kotlin/no/nav/veilarboppfolging/client/amttiltak/DeltakerDto.kt
Vi vil jo helst unngå å lage egne apier for hver konsument.. Men samtidig ser jeg det hensiktsmessige i at vi slipper å endre hos alle konsumentene hvis vi endrer på hva vi regner som en aktiv deltakelse 😅 Så ja, jeg kan lage et eget api for dette.

2024-06-05 11:52 UTC, tiafiring commented
> Jeg brukte litt tid på denne for å sikre at dette fungerer for praktiske formål. For å oppsummere: Så langt jeg kan se er det to caser der oppfølging avsluttes:
> 
> 1. arena-status endret (kafkamelding fra veilarbarena som plukker opp endringer på et materialisert view i arena)
> 2. synkront kall (fra visittkortet)
>    I det første tilfellet (hvis bruker har iserv-status) avsluttes ikke oppfølging umiddelbart, men bruker legges til en utmeldingstabell. Og en batch plukker ut brukere som har hatt isers mer enn 28 dager og forsøker å avslutte oppfølging.
>    Jeg har sjekket at i dette tilfellet vil man forsøke å avslutte bruker på nytt dersom det ikke lykkes etter 28 dager. Dette er jo litt nyttig, slik at bruker faktisk får avsluttet oppfølging hvis tiltaket avsluttes uten at man trenger å gjøre noe mer fra veileders side.
>    For det andre (synkrone) tilfellet, så vil jo oppfølging for bruker ikke blir avsluttet hvis bruker har et tiltak, men vi får ikke kommunisert med veileder hvorfor. Jeg tror vi må utvide  AvslutningStatus med et nytt felt 'aktivtTiltak' e.l. , og gjøre en liten justering i visittkortet, slik at veileder får en fornuftig feilmelding.
>    https://github.com/navikt/veilarboppfolging/blob/8b952825ef6156532b2e09c23ac9d4304e337de7/src/main/java/no/nav/veilarboppfolging/service/OppfolgingService.java#L420

Ja, her er det nok noe som mangler :)

2024-06-06 04:45 UTC, tiafiring commented on src/main/java/no/nav/veilarboppfolging/service/OppfolgingService.java
> +        Fnr fnr = authService.getFnrOrThrow(aktorId);
Fant en bedre løsning som gjorde at hele problemet forsvant :)

2024-06-26 08:11 UTC, holymaloney approved these changes

2024-06-26 08:33 UTC, merged