Gi SELECT-rettigheter på veilarboppfolging-schema til cloudsqliamuser
navikt/veilarboppfolging pull request #674
Opened 2024-10-23 06:52 UTC by slovrid

`nais postgres prepare veilarboppfolging` gir berre rettigheiter på `public`-schema. Inntil [støtte for custom-schema er på plass](https://github.com/nais/cli/issues/435) må vi sette dette sjølve.

2024-10-23 06:55 UTC, tu55eladd approved these changes

2024-10-23 06:57 UTC, tu55eladd approved these changes

2024-10-23 08:00 UTC, holymaloney requested changes

2024-10-23 08:00 UTC, holymaloney commented on src/main/resources/db/migration/V5__give-select-grant-for-cloudsqliamuser.sql
> +            GRANT SELECT ON ALL TABLES IN SCHEMA veilarboppfolging TO cloudsqliamuser;
Det er lurt å ha en `ALTER DEFAULT PRIVILEGUES` i tillegg, slik at man automatisk arver rettighetene for nye tabeller som blir opprettet.
Tror det blir noe a.la.
`ALTER DEFAULT PRIVILEGUES FOR ROLE cloudsqliamuser IN SCHEMA veilarboppgfolging GRANT SELECT ON ALL TABLES ;`

2024-10-24 05:32 UTC, slovrid commented
@holymaloney Gir du denne en ✅ dersom det ser greit ut?

2024-10-28 13:26 UTC, merged